const constants = {
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  WARNING: "WARNING",
  VALIDATION_ERROR: "Validation failed",
  VALIDATION_ERROR_MESSAGE:
    "Data validation error. Please try again and if problem persists then please contact administrator.",

  //========= WARNING ======
  ACTIVATION_MESSAGE: "Connect With admin for Activation of Account",

  // Possibilities Status Codes
  STATUS_OK: 200,
  STATUS_UPDATE: 201,
  STATUS_NOT_FOUND: 404,
  STATUS_SERVER_ERR: 500,

  //========= Success ==========
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  DELETE_RECORD: "DATA DELETE SUCCESSFULL",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  NEW_PASSWORD_SET_SUCCESS: "NEW_PASSWORD_SET_SUCCESS",
  FORGOT_EMAIL_SENT_SUCCESS: "FORGOT_EMAIL_SENT_SUCCESS",
  PROFILE_UPDATE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
  PROFILE_ADD_SUCCESS: "Account created successfully",
  RECORD_UPDATED_SUCCESS: "USER_UPDATED_SUCCESS",
  EMAIL_SEND: "Email Send",
  //====== Error ======

  EMAIL_DUPLICATE: "EMAIL_DUPLICATE",
  STATUS_BLOCK: "STATUS_BLOCK",
  CONNECTIVITY_ERROR: "CONNECTIVITY_ERROR",
  EMAIL_PASSWORD_ERROR: "Email or password incorrect",
  PHONE_NUMBER_PASSWORD_ERROR: "PHONE_NUMBER_PASSWORD_ERROR",
  PASSWORD_RESET_ERROR: "PASSWORD_RESET_ERROR",
  OLD_PASSWORD_ERROR: "OLD_PASSWORD_ERROR",
  FORGOT_PASSWORD_EMAIL_ERROR: "FORGOT_PASSWORD_EMAIL_ERROR",
  NO_SUCH_EMAIL: "NO_SUCH_EMAIL",
  REQUEST_EXPIRED: "REQUEST_EXPIRED_FOR_RESET_PASSWORD",
  EMAIL_SEND_ERROR: "Error in Sending Email",
};

module.exports = constants;
